apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: kueue-leader-election-rolebinding
  namespace: kueue-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kueue-leader-election-role
subjects:
- kind: ServiceAccount
  name: kueue-controller-manager
  namespace: kueue-system
