# Source: yunikorn/templates/admission-controller-secrets.yaml
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: admission-controller-secrets
  namespace: yunikorn
type: Opaque
---
# Source: yunikorn/templates/yunikorn-defaults.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-defaults
  labels:
    app: yunikorn
    chart: yunikorn-1.6.1
    release: yunikorn
    heritage: Helm
  annotations:
    "helm.sh/resource-policy": keep
data:
---
# Source: yunikorn/templates/admission-controller-service.yaml
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: yunikorn-admission-controller-service
  labels:
    app: yunikorn-admission-controller-service
    chart: yunikorn-1.6.1
    release: yunikorn
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: webhook-api
  selector:
    app: yunikorn
    component: yunikorn-admission-controller
    release: yunikorn
---
# Source: yunikorn/templates/service.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: yunikorn-service
  labels:
    app: yunikorn
    chart: yunikorn-1.6.1
    release: yunikorn
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - port: 9080
    targetPort: http1
    protocol: TCP
    name: yunikorn-core
  - port: 9889
    targetPort: http2
    protocol: TCP
    name: yunikorn-service
  selector:
    app: yunikorn
    component: yunikorn-scheduler
    release: yunikorn
---
# Source: yunikorn/templates/admission-controller-deployment.yaml
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yunikorn-admission-controller
  labels:
    app: yunikorn
    chart: yunikorn-1.6.1
    release: yunikorn
    heritage: Helm
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
      component: yunikorn-admission-controller
      release: yunikorn
  template:
    metadata:
      name: yunikorn-admission-controller
      labels:
        app: yunikorn
        component: yunikorn-admission-controller
        release: yunikorn
      annotations:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: yunikorn-admission-controller
      containers:
      - name: yunikorn-admission-controller
        image: "m.daocloud.io/docker.io/apache/yunikorn:admission-1.6.1"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: admission-controller-secrets
          mountPath: /run/secrets/webhook
          readOnly: true
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOMEMLIMIT
          value: "200MiB"
        - name: GOGC
          value: "100"
        ports:
        - containerPort: 9089
          name: webhook-api
        startupProbe:
          httpGet:
            scheme: HTTPS
            path: /health
            port: webhook-api
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /health
            port: webhook-api
          periodSeconds: 5
          failureThreshold: 3
      volumes:
      - name: admission-controller-secrets
        secret:
          secretName: admission-controller-secrets
---
# Source: yunikorn/templates/deployment.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yunikorn-scheduler
  labels:
    app: yunikorn
    chart: yunikorn-1.6.1
    release: yunikorn
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
      component: yunikorn-scheduler
      release: yunikorn
  template:
    metadata:
      name: yunikorn-scheduler
      labels:
        app: yunikorn
        component: yunikorn-scheduler
        release: yunikorn
      annotations:
    spec:
      serviceAccountName: yunikorn-admin
      containers:
      - name: yunikorn-scheduler-k8s
        image: "m.daocloud.io/docker.io/apache/yunikorn:scheduler-1.6.1"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http1
          containerPort: 9080
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOMEMLIMIT
          value: "1536MiB"
        - name: GOGC
          value: "100"
        resources:
          limits:
            cpu: 4
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
      - name: yunikorn-scheduler-web
        image: "m.daocloud.io/docker.io/apache/yunikorn:web-1.6.1"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http2
          containerPort: 9889
          protocol: TCP
        env:
        - name: GOMEMLIMIT
          value: "200MiB"
        - name: GOGC
          value: "100"
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
# Source: yunikorn/templates/ingress.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Source: yunikorn/templates/rbac.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Source: yunikorn/templates/admission-controller-rbac.yaml
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: yunikorn-admission-controller
  namespace: yunikorn
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yunikorn-admin
  namespace: yunikorn
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
---
# Source: yunikorn/templates/admission-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yunikorn-admission-controller-cluster-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "watch", "list"]
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yunikorn-scheduler
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
- apiGroups: ["yunikorn.apache.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
# Source: yunikorn/templates/admission-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yunikorn-admission-controller-cluster-rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: yunikorn-admission-controller
  namespace: yunikorn
roleRef:
  kind: ClusterRole
  name: yunikorn-admission-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yunikorn-rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: yunikorn-admin
  namespace: yunikorn
roleRef:
  kind: ClusterRole
  name: yunikorn-scheduler
  apiGroup: rbac.authorization.k8s.io
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yunikorn-rbac-kube-scheduler
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: yunikorn-admin
  namespace: yunikorn
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yunikorn-rbac-volume-scheduler
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: yunikorn-admin
  namespace: yunikorn
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
# Source: yunikorn/templates/admission-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yunikorn-admission-controller-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yunikorn-scheduler
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
# Source: yunikorn/templates/admission-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yunikorn-admission-controller-rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: yunikorn-admission-controller
  namespace: yunikorn
roleRef:
  kind: Role
  name: yunikorn-admission-controller-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: yunikorn/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yunikorn-rbac
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
subjects:
- kind: ServiceAccount
  name: yunikorn-admin
  namespace: yunikorn
roleRef:
  kind: Role
  name: yunikorn-scheduler
  apiGroup: rbac.authorization.k8s.io
