
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volcano-admission-init-role
  namespace: volcano-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
subjects:
- kind: ServiceAccount
  name: volcano-admission-init
  namespace: volcano-system
roleRef:
  kind: Role
  name: volcano-admission-init
  apiGroup: rbac.authorization.k8s.io
