
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volcano-admission-init
  namespace: volcano-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "patch", "get"]
