
kind: Deployment
apiVersion: apps/v1
metadata:
  name: volcano-scheduler
  namespace: volcano-system
  labels:
    app: volcano-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volcano-scheduler
  template:
    metadata:
      labels:
        app: volcano-scheduler
    spec:
      serviceAccount: volcano-scheduler
      priorityClassName: system-cluster-critical
      containers:
      - name: volcano-scheduler
        image: kind-registry:5000/docker.io/volcanosh/vc-scheduler:v1.12.0-alpha.0
        args:
        - --logtostderr
        - --scheduler-conf=/volcano.scheduler/volcano-scheduler.conf
        - --enable-healthz=true
        - --enable-metrics=true
        - --leader-elect=false
        - --kube-api-qps=1000 # <--QPS
        - --kube-api-burst=1000 # <--QPS
        - --schedule-period=1s
        - --node-worker-threads=100
        - -v=3
        - 2>&1
        env:
        - name: DEBUG_SOCKET_DIR
          value: /tmp/klog-socks
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: scheduler-config
          mountPath: /volcano.scheduler
        - name: klog-sock
          mountPath: /tmp/klog-socks
      volumes:
      - name: scheduler-config
        configMap:
          name: volcano-scheduler-configmap
      - name: klog-sock
        hostPath:
          path: /tmp/klog-socks
      terminationGracePeriodSeconds: 1
