apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /grafana/render/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: monitoring-grafana-image-renderer
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
        path: /grafana/grafana/render(/|$)(.*)
        pathType: ImplementationSpecific
